In [2]:
import pandas as pd

# Import data into pandas

In [245]:
event_codes = pd.read_csv("prompt/Event_Codes.txt", delimiter='\t')
game_lineup = pd.read_csv("prompt/Game_Lineup.txt", delimiter='\t')
play_by_play = pd.read_csv("prompt/Play_by_Play.txt", delimiter='\t')

### Sort play_by_play data

In [246]:
# sort the data by time
play_by_play.sort_values(by=['Game_id','Period','PC_Time','WC_Time','Event_Num'], ascending=[True,True,False,True,True], inplace=True)
play_by_play.reset_index(inplace=True, drop=True)

### Replace Team_ids in play_by_play data

In [256]:
game_ids = play_by_play['Game_id'].unique().tolist()
game_ids

['006728e4c10e957011e1f24878e6054a',
 '03ac65b9a32fde1e201bfb427f6e41e4',
 '096e231adad0be6ab1cc89cce56847f8',
 '117a5a71c34c2d8a39ff66d884462bd7',
 '1ea0a33aafb4a3cb31ba79cff049300c',
 '1ef70f0ed41e6862e3860613e3f21054',
 '25a5ddd58e1b7af731e179e2f98ed42f',
 '27caeb326b241334bfb308787974f959',
 '2877e9e9980619126420db0163ee0779',
 '32f2054d115f0b36efaa76e3a80a97d6',
 '3792cf8c80b4b4bda5e2aaeb403e96af',
 '394fd09c602f2cfe11644107673ae1c1',
 '3a4e6bebf52d096f4006d199ea7e1c16',
 '3b088c7d19b1d7b56f5842e39b29e06d',
 '3ce947db2df86b08a40b7526e2faaccb',
 '403719b7c2a6208e817387e06ffefb77',
 '426251168251f96f7ea501fcd0dafa7c',
 '476e6303a0d6728a5848a179a119bb32',
 '4c586da09a05a775832969387305b688',
 '4d475b083c4c975deabe3d9bfe98dd90',
 '559912f00a5ed116f71cb72ecc991a5b',
 '58f4e85cad83adedfa96749b0cde2564',
 '5a2bb80caeb8ee7d84bca860e2c38249',
 '62083f5d100803b41537d7afa1de25b3',
 '624e85db99e59ea7bbbdc0f74923f645',
 '681bafe84c48e522bc72eba7b3a04b4a',
 '68f62f1c5cb84257932676bef8cc7a1a',
 '6b17d80707e8791747fabb15c754a6e7',
 '70a984edc9dc4badf5c6be5835d6bdd4',
 '72deb55b6e864b5d58cd2900bf4079b4',
 '7a5f149ff86cedd8abfdd28358b88786',
 '7b1e12cfc67be542ac404f3d9389b9dc',
 '7b4b6c18c831bc54239f663d0e604497',
 '8145bdb1a51e43529f41a4f640e9a306',
 '87e27d0359dcbf480739ad0c2000a214',
 '890600997c60cca3e41236355c65642e',
 '8a2f954e8d303e73de01bd620b1ef6c3',
 '8d607031b304748acd198851fca5321c',
 '95770267429c4b7118a82bb8b4f2be54',
 '97b18f77e14984e2ed00a5962eb6145d',
 '97b8982d363b55efc61eae5d969d7f44',
 '9892e70d668a7287f5460350b8a6afdf',
 '9b718cc561cecf4da6d0632def573409',
 '9da3345a6665c45dac22d04f78d8a355',
 '9fac61d1e1988c53408cfc2578f2c683',
 'a466c76e072fd634f6d4a8938fb63caa',
 'a48be9b24719a0473155288a5c081448',
 'a69272714a8340233730bd697769b261',
 'a83f772456480ca41ef5fbe62ce70c7e',
 'ac246b4083eff03543a7d58536808eb4',
 'acf9fc13f76192889b8ae5c28d229591',
 'b2b580f1d233c5b3d115028275714306',
 'b6badbf582ad7c8e52c35cb5308e3ffb',
 'b7a1056b097e5e604925867c0ca17442',
 'baa3708b350d01ba0c12fd2a89b1c3d9',
 'bb4e1b593cc210dec5fdcb0f7eb4739d',
 'bbdfa92c4ade547643cd69741f736b21',
 'c09f006fc1ed45361310b19c235dbf72',
 'c719eacc4252db10ae57c92a8a8e17d2',
 'c846ca699a9e1d795540ac3f59e72d80',
 'c8ebe24f264e733f64003130d7d5e18d',
 'c92a96dcef0009c7d3583cd2e603099c',
 'c9353934036e5c77258f2b7ab7685e79',
 'c97b18a3f671fd9bd4648cb84125ac6b',
 'ca963a5c2830ee97acee003347515654',
 'd03a92390eb3db203f36d0d89ee9c0b9',
 'd2bc9ecd1c1dca587901bcc901896076',
 'd36de5306a05d0cdbd51a7294ac91359',
 'd508da19217d10b9a4566ef06184b4fd',
 'd522ea3836b8e1977ab10b3bfeb5dfd1',
 'db01d0f50dbdc57e0346858ac7be154a',
 'dc3a96d83623f28fd84bd535e57c146f',
 'df46ea1ec9250af2cd2f8e48f705ba4a',
 'e08f26c110e19f7afa4cbe5aed43be4a',
 'e4ea5ad257a30f4a3c06683e0186bd6d',
 'e9db074d4b4bb862dde70d545e3ac13f',
 'ea198bf717f42cdfc94c577faaf39666',
 'ed95a454eee025e4b93e217ad6a578f1',
 'efca551b622ff96393fb43947e1aad4b',
 'f280a671f82eb32b48f00116b8956445',
 'f959bc122b1ee996f3e12bc61c068ad4',
 'ff42c1cba89fd3f3a7a6711a11d5576d']

In [259]:
"""
replace team_ids in play_by_play data.
some team_ids in raw data are incorrect.
team_ids in game_lineup dataframe are always correct.
"""

new_play_by_play = play_by_play.copy()


print(play_by_play.shape)

# FIGURE OUT HOW TO REPLACE TEAM IDS

for game_id in game_ids:
    player_to_team_map = {}
    
    game_data = game_lineup[(game_lineup['Game_id'] == game_id) & (game_lineup['Period'] == 0)].copy()
    # map player_ids to team_id for one game
    for idx, row in game_data.iterrows():
        player_id = row['Person_id']
        team_id = row['Team_id']
        if player_id not in player_to_team_map:
            player_to_team_map[player_id] = team_id
    
    play_by_play_data = play_by_play[play_by_play['Game_id'] == game_id]
    
    for idx, row in play_by_play_data.iterrows():
        
        
    

    
print(play_by_play.shape)

ae53f8ba6761b64a174051da817785bc
44230324724c84f122ac62a5f0918314
8d2127290c94bd41b82a2938734bc750
48ec4e6c52f418d5ca4ef510ba473ea0
e816ff284dc3f965b8f3d605a3b91bae
ed95dff5440fadf3042b5acacea81eed
616281dee946056b071699476fdee9ec
e814950408915f43de2b079dce7c21c5
2ad626904c8b28cceb8e12c624a84240
bd45fe7dba52aa2cd00ba80ff107d05b
766802a8fda500d7945950de7398c9c6
99104de2626f67c1fa2ce70504970c3f
42e0d7167f04a4ff958c6442da0e6851
c5dd5b2e3b975f0849d9b74e74125cb9
5db9c1c8184510fee8161e7fafdc9c49
f4a5ca938177c407a9dab5412e39498f
1b37fed4823f31ccbf03515f4b9fe438
c10b49616a2f4a23607dc1a8be4fde9f
d00d552bc4e50f63f9397a74514519ba
dd1da128c27db468d95b99b583f8a57d
4ef3dae16c436459ff05156abca5cebd
618f6d58ab2881152607c2a6e057bc51
902362537ff2a39c0c0cfb82ab0adac2
e59b921ab3da55f632bc748beb12805a
4413c19cf092bda39332d7833c90bfe6
bf6ed471f8425903310f08548a206905
5cce6ffa455e6372d9de0de400482ab6
4dd3d6a51dc97c651d3a86eec4362a1f
7027df5d9c51192f3527ac8c74b4d08d
d81d912f81fa43178f423aa89a713e96

In [23]:
event_codes.head()

,Event_Msg_Type,Action_Type,Event_Msg_Type_Description,Action_Type_Description
0,1,0,Made Shot,No Shot
1,1,1,Made Shot,Jump Shot
2,1,2,Made Shot,Running Jump Shot
3,1,3,Made Shot,Hook Shot
4,1,4,Made Shot,Tip Shot

In [24]:
game_lineup.head()

,Game_id,Period,Person_id,Team_id,status
0,006728e4c10e957011e1f24878e6054a,0,ae53f8ba6761b64a174051da817785bc,01be0ad4af7aeb1f6d2cc2b6b6d6d811,A
1,006728e4c10e957011e1f24878e6054a,0,44230324724c84f122ac62a5f0918314,45ba8fc87f55b1191c50c400dc7ed11c,A
2,006728e4c10e957011e1f24878e6054a,0,8d2127290c94bd41b82a2938734bc750,01be0ad4af7aeb1f6d2cc2b6b6d6d811,A
3,006728e4c10e957011e1f24878e6054a,0,48ec4e6c52f418d5ca4ef510ba473ea0,45ba8fc87f55b1191c50c400dc7ed11c,A
4,006728e4c10e957011e1f24878e6054a,0,e816ff284dc3f965b8f3d605a3b91bae,01be0ad4af7aeb1f6d2cc2b6b6d6d811,A

In [249]:
play_by_play.head()

,Game_id,Event_Num,Event_Msg_Type,Period,WC_Time,PC_Time,Action_Type,Option1,Option2,Option3,Team_id,Person1,Person2,Person3,Team_id_type,Person1_type,Person2_type,Person3_type
0,006728e4c10e957011e1f24878e6054a,2,12,1,546410,7200,0,0,0,0,1473d70e5646a26de3c52aa1abd85b1f,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,0,0,0,0
1,006728e4c10e957011e1f24878e6054a,4,10,1,546420,7200,0,0,0,0,01be0ad4af7aeb1f6d2cc2b6b6d6d811,8d2127290c94bd41b82a2938734bc750,99104de2626f67c1fa2ce70504970c3f,766802a8fda500d7945950de7398c9c6,2,4,5,4
2,006728e4c10e957011e1f24878e6054a,7,1,1,546590,7020,79,2,0,0,01be0ad4af7aeb1f6d2cc2b6b6d6d811,42e0d7167f04a4ff958c6442da0e6851,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,2,4,0,0
3,006728e4c10e957011e1f24878e6054a,8,6,1,546620,7020,2,0,0,1,01be0ad4af7aeb1f6d2cc2b6b6d6d811,616281dee946056b071699476fdee9ec,42e0d7167f04a4ff958c6442da0e6851,0b1c631effab25d4af2d16fc123c3d31,2,5,4,1
4,006728e4c10e957011e1f24878e6054a,10,3,1,546810,7020,10,1,0,0,01be0ad4af7aeb1f6d2cc2b6b6d6d811,42e0d7167f04a4ff958c6442da0e6851,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,2,4,0,0

# Brief Overlook of the Data

In [35]:
# number of games we need to process
play_by_play['Game_id'].unique().shape[0]

82

In [250]:
play_by_play[(play_by_play['Event_Msg_Type'] == 6) & (play_by_play['Action_Type'] == 14)]
# play_by_play.iloc[746-5:746+5,:]

,Game_id,Event_Num,Event_Msg_Type,Period,WC_Time,PC_Time,Action_Type,Option1,Option2,Option3,Team_id,Person1,Person2,Person3,Team_id_type,Person1_type,Person2_type,Person3_type
746,03ac65b9a32fde1e201bfb427f6e41e4,437,6,3,727180,2530,14,0,0,2,cd45058739ed0ac8229849c6249aad48,41c0674725d4cddab004649e9db5a3ce,ff59dc439c6c323320bc355afe884fcb,aa3b80d27f18c221408b698c7d89d250,2,5,4,1
1154,096e231adad0be6ab1cc89cce56847f8,344,6,3,632700,6110,14,0,0,2,01be0ad4af7aeb1f6d2cc2b6b6d6d811,48ec4e6c52f418d5ca4ef510ba473ea0,c5dd5b2e3b975f0849d9b74e74125cb9,4c28632a1ac678cf75a2110234adbf29,2,5,4,1
3841,2877e9e9980619126420db0163ee0779,304,6,2,610470,1400,14,0,0,2,e2d25dd55740327314a2a0b874621ba8,16d76c912992709c8be29b896b8f9417,f85a47779c423d73ea3b2aa48c54ff8b,24b95770922cd7772df8e5250e86a702,2,5,4,1
7196,403719b7c2a6208e817387e06ffefb77,587,6,4,760020,2670,14,0,0,2,bcdf0d0117f2e3d5afcd70f977eae3d6,a1591595c04d12e88e3cb427fb667618,d63f6d3cb837e14523a89546ff649ed7,6095bcbf4e6a692492b2d9f0a3b975a8,3,4,5,1
8080,476e6303a0d6728a5848a179a119bb32,562,6,4,677270,2290,14,1,0,2,0a6fc39f34702cff144525dfd265f8fa,7f438c18058290903c46dfe9d71bd68a,95c8abc40fb4ecf4fa5627975450dc95,81efe876f336ab00d7331d21e9ac06dd,2,5,4,1
10750,62083f5d100803b41537d7afa1de25b3,476,6,4,615140,5010,14,0,0,2,8362dfecb7412f12a12713852d2ae566,137eed94de2c9698e4ac04e9ae73df02,fb64ca4b8beaf4c4c6e4575fe2f3abd7,6095bcbf4e6a692492b2d9f0a3b975a8,2,5,4,1
24136,b6badbf582ad7c8e52c35cb5308e3ffb,353,6,3,594980,5730,14,0,0,2,0a6fc39f34702cff144525dfd265f8fa,8ef226e011978823e53492a28d71217f,3007e387a7d41a704390cb5878271b9a,e6316849fc94da16ecfd25fa67cf8c17,2,5,4,1
25436,bb4e1b593cc210dec5fdcb0f7eb4739d,278,6,2,508440,1240,14,0,0,2,b5464c11e1a8a18452a7d2988badfe0c,2c447ab0a100cb50766552b0f6fadc2d,6ad10958a1d4920dccb1daec39bebd6b,5201a0c1055bebf092c5ce178e5c7863,2,5,4,1
31530,d508da19217d10b9a4566ef06184b4fd,465,6,4,557970,6020,14,0,0,2,45ba8fc87f55b1191c50c400dc7ed11c,f4a5ca938177c407a9dab5412e39498f,48ec4e6c52f418d5ca4ef510ba473ea0,8b8d9227a96ad6ed93838617e3a2319a,2,5,4,1
33805,e08f26c110e19f7afa4cbe5aed43be4a,260,6,2,574740,2920,14,0,0,1,45ba8fc87f55b1191c50c400dc7ed11c,ae53f8ba6761b64a174051da817785bc,616281dee946056b071699476fdee9ec,81efe876f336ab00d7331d21e9ac06dd,2,5,4,1
37447,ff42c1cba89fd3f3a7a6711a11d5576d,68,6,1,517570,4290,14,0,0,2,01be0ad4af7aeb1f6d2cc2b6b6d6d811,99104de2626f67c1fa2ce70504970c3f,766802a8fda500d7945950de7398c9c6,07d9e91acd630847d464ab580db967e7,2,5,4,1

# Information

### Event_msg_type documentation:
    1   -->   Made Shot              (add points, possession ends & changes)
    2   -->   Missed Shot            (don't add points, don't change possession --> DONT CARE)
    3   -->   Free Throw             (add points, possession remain same)
    4   -->   Rebound                (possesion could change, remain same)
    5   -->   Turnover               (possession changes)
    6   -->   Foul                   (don't add points, don't change possession) (what about offensive foul though?? does a turnover event follow?)
    7   -->   Violation              (what about offensive violation though?? does a turnover event follow?)
    8   -->   Substitution           (change active players)
    9   -->   Timeout                (DONT CARE)
    10  -->   Jumpball               (gotta figure out possession after jumpball)
    11  -->   Ejection               (DONT CARE)
    12  -->   Start Period
    13  -->   End Period             (possession ends)
    14  -->   Validation             (DIDNT EXIST)
    15  -->   Memo                   (DIDNT EXIST)
    16  -->   Final Box Printed      (DONT CARE)
    18  -->   Instant Replay         (DONT CARE)
    20  -->   Stoppage               (DONT CARE)
    
    
### Final Deliverable
    """
    +-------------+---------------+------------+------------+
    |   Game_ID   |   Player_ID   |   OffRtg   |   DefRtg   |
    +-------------+---------------+------------+------------+
    """

# Define Classes

In [152]:
class Game():
    """
    Records all the information of one game
    """
    def __init__(self, game_id, df_play_by_play, df_game_lineup):
        self.game_id = game_id
        self.df_play_by_play = df_play_by_play.copy()
        self.df_game_lineup = df_game_lineup.copy()
        
        # get the 2 teams of this game
        self.team_A_id, self.team_B_id = self.df_game_lineup['Team_id'].unique().tolist()
        
        # get the players of the 2 teams
        self.team_A_players = self.df_game_lineup[self.df_game_lineup['Team_id'] == self.team_A_id]['Person_id'].unique().tolist()
        self.team_B_players = self.df_game_lineup[self.df_game_lineup['Team_id'] == self.team_B_id]['Person_id'].unique().tolist()
        
        # create 2 Team objects
        self.team_A = Team(self.game_id, self.team_A_id, self.team_A_players)
        self.team_B = Team(self.game_id, self.team_B_id, self.team_B_players)
        
        # sort the play_by_play data
        self.df_play_by_play.sort_values(by=['Period','PC_Time','WC_Time','Event_Num'], ascending=[True,False,True,True], inplace=True)
        
        # keep track of possession
        team_on_offense = ""
        team_on_defense = ""
        
        
        
        
    def __str__(self):
        ret = "Game ID:\t{}\n".format(self.game_id)
        ret += "\n\tTeam A ID:\t{}\n".format(self.team_A_id)
        ret += "\tTeam B ID:\t{}\n\n".format(self.team_B_id)
        return ret
    
    def check_team(player_id):
        if player_id in self.team_A_players:
            return self.team_A_id
        if player_id in self.team_B_players:
            return self.team_B_id
    
    def process_one_row(self):
        """
        Processes one row of play_by_play data
        """
        
        pass
    
    def points_scored(self):
        pass
    
    def possession_ends(self):
        pass
    
    def free_throw(self):
        pass
    
    def substitution(self):
        pass

In [254]:
class Team():
    """
    Records all the information of one team in one game
    """
    def __init__(self, game_id, team_id, player_ids_list = []):
        self.game_id = game_id
        self.team_id = team_id
        
        # player_ids mapped to corresponding Player object
        self.roster = {}
        for player_id in player_ids_list:
            self.roster[player_id] = Player(self.game_id, self.team_id, player_id)
        
        # need 2 active lists to keep track of active players during fouls/free throws
        self.active_1 = []
        self.active_2 = []
        
    
    def __str__(self):
        ret = "Team ID:\t{}\n\n".format(self.team_id)
        for idx, player_id in enumerate(self.roster):
            ret += "\tPlayer {}:\t{}\n".format(idx+1, player_id)
        
        return ret
        
    
    def get_player(self, player_id):
        return self.roster[player_id]
    
    def add_points_scored(self, points):
        for player_id in self.active_1:
            self.roster[player_id].add_points_scored(points)
        
    def add_points_allowed(self, points):
        for player_id in self.active_1:
            self.roster[player_id].add_points_allowed(points)
    
    def add_off_possessions(self, number):
        for player_id in self.active_1:
            self.roster[player_id].add_off_possessions(points)
    
    def add_def_possessions(self, number):
        for player_id in self.active_1:
            self.roster[player_id].add_def_possessions(points)
    
    def substitute(self):
        pass

In [187]:
class Player():
    def __init__(self, game_id, team_id, player_id):
        self.game_id = game_id
        self.team_id = team_id
        self.player_id = player_id
    
        self.points_scored = 0
        self.points_allowed = 0
        self.off_possessions = 0
        self.def_possessions = 0
    
    def __str__(self):
        ret = "Player ID: {}\n".format(self.player_id)
        ret += "\tPoints Scored: {}\n".format(self.points_scored)
        ret += "\tPoints Allowed: {}\n".format(self.points_allowed)
        ret += "\tPossessions: {}\n".format(self.possessions)
        ret += "\tOffensive Rating: {}\n".format(self.get_offensive_rating())
        ret += "\tDefensive Rating: {}\n".format(self.get_defensive_rating())
        
        return ret
    
    def add_points_scored(self, points):
        self.points_scored += points
        
    def add_points_allowed(self, points):
        self.points_allowed += points
    
    def add_off_possessions(self, number):
        self.off_possessions += number
    
    def add_def_possessions(self, number):
        self.def_possessions += number
    
    def get_offensive_rating(self):
        return self.points_scored / self.off_possessions * 100 if self.off_possessions != 0 else 0
    
    def get_defensive_rating(self):
        return self.points_allowed / self.def_possessions * 100 if self.def_possessions != 0 else 0

# Testing out Class functions with one game

In [122]:
test_game_id = "006728e4c10e957011e1f24878e6054a"

In [123]:
test_play_by_play = play_by_play[play_by_play['Game_id'] == test_game_id].copy()
test_play_by_play.head()

,Game_id,Event_Num,Event_Msg_Type,Period,WC_Time,PC_Time,Action_Type,Option1,Option2,Option3,Team_id,Person1,Person2,Person3,Team_id_type,Person1_type,Person2_type,Person3_type
0,006728e4c10e957011e1f24878e6054a,2,12,1,546410,7200,0,0,0,0,1473d70e5646a26de3c52aa1abd85b1f,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,0,0,0,0
1,006728e4c10e957011e1f24878e6054a,4,10,1,546420,7200,0,0,0,0,01be0ad4af7aeb1f6d2cc2b6b6d6d811,8d2127290c94bd41b82a2938734bc750,99104de2626f67c1fa2ce70504970c3f,766802a8fda500d7945950de7398c9c6,2,4,5,4
2,006728e4c10e957011e1f24878e6054a,7,1,1,546590,7020,79,2,0,0,01be0ad4af7aeb1f6d2cc2b6b6d6d811,42e0d7167f04a4ff958c6442da0e6851,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,2,4,0,0
3,006728e4c10e957011e1f24878e6054a,8,6,1,546620,7020,2,0,0,1,01be0ad4af7aeb1f6d2cc2b6b6d6d811,616281dee946056b071699476fdee9ec,42e0d7167f04a4ff958c6442da0e6851,0b1c631effab25d4af2d16fc123c3d31,2,5,4,1
4,006728e4c10e957011e1f24878e6054a,10,3,1,546810,7020,10,1,0,0,01be0ad4af7aeb1f6d2cc2b6b6d6d811,42e0d7167f04a4ff958c6442da0e6851,0370a0d090da0d0edc6319f120187e0e,0370a0d090da0d0edc6319f120187e0e,2,4,0,0

In [181]:
test_game_lineup = game_lineup[game_lineup['Game_id'] == test_game_id].copy()
test_game_lineup.head()

,Game_id,Period,Person_id,Team_id,status
0,006728e4c10e957011e1f24878e6054a,0,ae53f8ba6761b64a174051da817785bc,01be0ad4af7aeb1f6d2cc2b6b6d6d811,A
1,006728e4c10e957011e1f24878e6054a,0,44230324724c84f122ac62a5f0918314,45ba8fc87f55b1191c50c400dc7ed11c,A
2,006728e4c10e957011e1f24878e6054a,0,8d2127290c94bd41b82a2938734bc750,01be0ad4af7aeb1f6d2cc2b6b6d6d811,A
3,006728e4c10e957011e1f24878e6054a,0,48ec4e6c52f418d5ca4ef510ba473ea0,45ba8fc87f55b1191c50c400dc7ed11c,A
4,006728e4c10e957011e1f24878e6054a,0,e816ff284dc3f965b8f3d605a3b91bae,01be0ad4af7aeb1f6d2cc2b6b6d6d811,A

In [182]:
test_game = Game(test_game_id, test_play_by_play, test_game_lineup)

In [183]:
print(test_game)

Game ID:	006728e4c10e957011e1f24878e6054a

	Team A ID:	01be0ad4af7aeb1f6d2cc2b6b6d6d811
	Team B ID:	45ba8fc87f55b1191c50c400dc7ed11c

In [184]:
print(test_game.team_B)

Team ID:	45ba8fc87f55b1191c50c400dc7ed11c

	Player 1:	44230324724c84f122ac62a5f0918314
	Player 2:	48ec4e6c52f418d5ca4ef510ba473ea0
	Player 3:	616281dee946056b071699476fdee9ec
	Player 4:	e814950408915f43de2b079dce7c21c5
	Player 5:	99104de2626f67c1fa2ce70504970c3f
	Player 6:	1b37fed4823f31ccbf03515f4b9fe438
	Player 7:	d00d552bc4e50f63f9397a74514519ba
	Player 8:	4ef3dae16c436459ff05156abca5cebd
	Player 9:	902362537ff2a39c0c0cfb82ab0adac2
	Player 10:	4413c19cf092bda39332d7833c90bfe6
	Player 11:	bf6ed471f8425903310f08548a206905
	Player 12:	5cce6ffa455e6372d9de0de400482ab6
	Player 13:	4dd3d6a51dc97c651d3a86eec4362a1f
	Player 14:	7027df5d9c51192f3527ac8c74b4d08d
	Player 15:	d81d912f81fa43178f423aa89a713e96

In [185]:
for player in test_game.team_B.roster:
    print(test_game.team_B.roster[player])

Player ID: 44230324724c84f122ac62a5f0918314
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 48ec4e6c52f418d5ca4ef510ba473ea0
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 616281dee946056b071699476fdee9ec
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: e814950408915f43de2b079dce7c21c5
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 99104de2626f67c1fa2ce70504970c3f
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 1b37fed4823f31ccbf03515f4b9fe438
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: d00d552bc4e50f63f9397a74514519ba
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 4ef3dae16c436459ff05156abca5cebd
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 902362537ff2a39c0c0cfb82ab0adac2
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 4413c19cf092bda39332d7833c90bfe6
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: bf6ed471f8425903310f08548a206905
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 5cce6ffa455e6372d9de0de400482ab6
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 4dd3d6a51dc97c651d3a86eec4362a1f
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: 7027df5d9c51192f3527ac8c74b4d08d
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0

Player ID: d81d912f81fa43178f423aa89a713e96
	Points Scored: 0
	Points Allowed: 0
	Possessions: 0
	Offensive Rating: 0
	Defensive Rating: 0